#include "Menu/Menu.h"
#include <stdio.h>
#include "Functions/GeneralFunctions.h"

int main()
{
    //char test[] = "sxukwydpckwrmipdegxxfkxnrmjoeqpseqlynrmdezcildibrmkcijpjpyqjyrbyrdyvkkrwiiybwrrsqoafyacbifyrmevcnfwkfcdxcbeaayysrrkraoagdlfsqrreldlcbiqdhcmpybibdlydrmlsbigmepbzvcdilnxmretoitovqoilrmkkrwglcbicvwcrmqcsjotycxgwiqgipovckhgxkrrinktcbwyxhnvewsreglgcxfosddilgslkxrrmqqekoafsgfkwycmjorryrcrepwslswcnagdlfswlkxsbizexfswusrlsrecrcfipgildmldsfswnevqofcsrebiqovtohycederbpsprmqmlybmrsiqwvdykezpyiibxsrdsusrzexdyvrriqkocyjnvewsredlcqekoaycmlrmqoccceayrrowrkwrbyeqpcgmrrebsjdsgsvxwiirkqmdmmxpccwsxackvwsrecxpekeviayreorgkprylgcxycxcctfspckwdykegeqxsrurmgrrylyficsxfovusjcyvarmjnvcxafsgfwewrenzildsrrikywrrslowrzimzpcomrripbijkxgfiqyvloeppvgorbcafsgfswaovrkmlvckyvcerscyyvlcvmtohyvslomlrmqrsscigxwyfmjvipyaurmrripxslotcxirberohycmlqpcnskowrsgqejdsgcnxmcipfifsqfofpoeipeqdibkrbnmlohydxfogjefydlmevqwerrikkxgmejvcdsbcnmldlccekovmyqydxfowywirkfjorcfipdeisrermqwiyvwusxfyxfovkoqzovqwyarpccwzbmlqmlqeeeiqdagdlfsqyxhuorrrskoerobymxjiqgnrgqlryrjixmbirsvckxmxgcdszohforcfipewcnxfogmccareklipcafsgfdlcbidyvkzvmfmbowdyvgdwdkzmevcnqcwfcbwfotycwcnxcxlmevqyyryjrrirgildcdyypsrqkzgvpcbsuomrripsrqviczmlqspweisrermqdsgvirglcxlcmlmciryxyuiygejumrgeqgmrrepoksvepcxczmldlcorrbelmifkpjgmrrmrcqmcegmjjyspsreyvgxxfoggbgsvepqejvipiagdlgdwbyqccynzspdiblcrgildcpohnyvnrcpimmxmamsjeqlcelnmjvyksrcnfwlpsotysrrohusrbyaqglcxlclvckodkwrohmbhgxibkpjdlcbiqyypmiqyjrriavyzsxqumrmlcxwyxhnkrrbmccmrcfsdxcbcyxhbkmpiegnibdsabsunlgcxylpcgmrrxfompwsqdwsmgsvildwryvcclcgeqcipfiblcrriebetowrgegdipcmlnvccwayercelnwfyiqgmrrwukrqumlcsjowursnbsdpipohrritselnwgxwnoggkpnyvaopysryxhmxxfojgxiqdpgxilmpslhcmeldipcsdkpmcxkyyjngmxxysrcnlgcwfovpilgctmbxyxhfswasrlkqmxwnsgcngjkvcdafspcrmqlitovyqiqgipovcpvcclgxkjigmypcnagdlgmizbssqlrkxebiydgmcxdbskdlckqcbmakrjkocc";
    Initialize_App();
    //Initialize_Data();
    //char keyword[11];
    //CeaserCrack(keyword, 10);
    //printf("\nkeyword: %s\n", Session.keyword);

    ExitApp(0);
    return 1;
}
